meta_product_name: "Oy"
meta_title: "Oy - Make loyalty cards great again"
meta_description: "Oy is an app willing to bring small business’s owners and clients closer. Go outside, and try the small coffee you always said you would."
meta_image: "oy-cover.png" # should exist in `app/assets/images/`
